Repository peopleware/angular-sdk, pull requests merged in 2025-05, with the labels that each got.

#42 feat(router): get full route path without leading slash
  projects/ppwcode/ng-router/src/lib/route-map/route-retrieval.spec.ts
  projects/ppwcode/ng-router/src/lib/route-map/route-retrieval.ts
Labels: target: minor

#43 feat(router): introduce defineContainer
  projects/ppwcode/ng-router/src/lib/route-map/define-route.spec.ts
  projects/ppwcode/ng-router/src/lib/route-map/define-route.ts
  projects/ppwcode/ng-router/src/lib/route-map/pipes/route-map-route.spec.ts
  projects/ppwcode/ng-router/src/lib/route-map/pipes/route-map-segment.spec.ts
  projects/ppwcode/ng-router/src/lib/route-map/route-map-route.ts
  projects/ppwcode/ng-router/src/lib/route-map/route-retrieval.spec.ts
  projects/ppwcode/ng-router/src/lib/route-map/route-retrieval.ts
  projects/ppwcode/ng-router/src/lib/route-map/testing/get-full-route-map-urls.ts
Labels: target: minor

#45 feat(forms): extend form control generators to accept async validators
  projects/ppwcode/ng-forms/src/lib/generators.spec.ts
  projects/ppwcode/ng-forms/src/lib/generators.ts
Labels: target: minor, type: feature

#46 Add isInitiallyPending boolean parameter to the isPending function to…
  projects/ppwcode/ng-common/src/lib/mixins/track-pending.ts
Labels: type: bug

#47 Feature/dashboard actions direction
  projects/ppwcode/ng-common-components/src/lib/dashboard-items/dashboard-items-table/dashboard-items-table.component.html
  projects/ppwcode/ng-common-components/src/lib/dashboard-items/dashboard-items-table/dashboard-items-table.component.scss
  projects/ppwcode/ng-common-components/src/lib/dashboard-items/models/dashboard-item.model.ts
  src/app/dashboard-item-demo/dashboard-item-demo.component.ts
Labels: target: minor, type: feature
